### ISSUE TITLE
Is it possible to get past the 30FPS output limit when sampling input with let's say 1000FPS?

### ISSUE THREAD

**Issue by FabianRudolph** [SensorsINI/v2e#70]
I would like to get the same fps for the output as I put in as a video. Thank you in advance!

**Comment by duguyue100** [comment]
Hi, thanks for the interest, v2e doesn't implicitly speed up or down the video frame rates, it just processes the frame rate as given. However, the rendered video playback does have a preset frame rate which you can adjust with `avi_frame_rate` option.

I would recommend that you post-process the events yourselves though because the playback is mainly used as a visualization and does some additional processing to look nicer.
